# -*- coding: utf-8 -*-
"""PCD _Assignment01_558659_Jasmine

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c2jrOSSnV6LAEVPXQFC0UxRj_jwSKk3Z

# **Digital Image Processing Assignment 1**
"""

import numpy as np
import cv2
import matplotlib.pyplot as plt
from scipy import ndimage

"""Insert picture from drive"""

from google.colab import drive

drive.mount('/content/drive', force_remount=True)

image_path = '/content/drive/MyDrive/semester 3/Digital Image Processing/Assignment 1/dolly parton 2.jpg'
img = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)

"""down sampling"""

def avgmethod_downsampling(image):
    kernel = np.ones((8, 8)) / 64
    return ndimage.convolve(image, kernel)[::8, ::8]

def medianmethod_downsampling(image):
    return ndimage.median_filter(image, size=8)[::8, ::8]

def maxmethod_downsampling(image):
    return ndimage.maximum_filter(image, size=8)[::8, ::8]

avg_img = avgmethod_downsampling(img)
med_img = medianmethod_downsampling(img)
max_img = maxmethod_downsampling(img)

"""display down sampling"""

images = [img, avg_img, med_img, max_img]
titles = ['Original', 'Average (8x)', 'Median (8x)', 'Max (8x)']

plt.figure(figsize=(12, 12))
for i in range(4):
    plt.subplot(1, 4, i + 1)
    plt.imshow(images[i], cmap='gray')
    plt.title(titles[i])
    plt.axis('off')

plt.show()

"""insert different image from drive"""

from google.colab import drive

drive.mount('/content/drive', force_remount=True)

image_path = '/content/drive/MyDrive/semester 3/Digital Image Processing/Assignment 1/low res dolly parton.jpg'
img = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)

"""up sampling"""

def nn_upsampling(image):
    h, w = image.shape
    return cv2.resize(image, (w * 8, h * 8), interpolation=cv2.INTER_NEAREST)

def bilinear_upsampling(image):
    h, w = image.shape
    return cv2.resize(image, (w * 8, h * 8), interpolation=cv2.INTER_LINEAR)

def bicubic_upsampling(image):
    h, w = image.shape
    return cv2.resize(image, (w * 8, h * 8), interpolation=cv2.INTER_CUBIC)

nn_img       = nn_upsampling(img)
bilinear_img = bilinear_upsampling(img)
bicubic_img  = bicubic_upsampling(img)

"""display up sampling"""

images = [img, nn_img, bilinear_img, bicubic_img]
titles = ['Low-Res Original', 'Nearest Neighbor (8x)', 'Bilinear (8x)', 'Bicubic (8x)']

plt.figure(figsize=(12, 12))
for i in range(4):
    plt.subplot(1, 4, i + 1)
    plt.imshow(images[i], cmap='gray')
    plt.title(titles[i])
    plt.axis('off')

plt.show()